### ISSUE TITLE
May I use the database made from this program in my own program?

### ISSUE THREAD

**Issue by MeLikeChoco** [chinhodado/YgoSqliteDbCreator#1]
I apologize for this method of contact as I found no other open way.

May I use your ygo.db database for my own program?
Of course, credit for the database will not be taken at all.
I merely wish to access these to parse data, all files from and generated by your program will not be present on any computer but mine and my own server's storage.

The program is located here: https://github.com/MeLikeChoco/YuGiOhBot
I was going to use DevPro's or YgoPro's database, however, yours is much easier to parse and read. I also have the problem of permissions due to their lack of presence in communication services.
Although the database your program generates contains less entries, I am sure we could find the differences.

Thank you!

**Comment by chinhodado** [comment]
Sure, you can use the database for whatever purpose you wish, I have no problem with that whatsoever.

**Comment by MeLikeChoco** [comment]
Thank you very much! I have some followup questions. 
1. How long do you think this will be maintained?
2. As a sign of gratitude, may I promote your app with my program?

**Comment by chinhodado** [comment]
The app is updated about once a month. You can always run this script to generate the database yourself whenever you want, though don't do it too often cause wikia may not be too happy about it...

Sure I wouldn't mind you promoting the app. Thanks in advance.

**Comment by MeLikeChoco** [comment]
I have noticed you do not pull archetypes. Having a column for archetypes would be very useful as searching with strings of known archetypes in name and lore columns is highly inaccurate. The wikia does provide information to if the card is in any archetype as seen here: 
![image](https://cloud.githubusercontent.com/assets/8294061/24265290/5cd581fc-0fd9-11e7-910d-238826dd3c19.png)

**Comment by chinhodado** [comment]
Yeah this has been planned for a while. I will get to it once I find enough time and motivation. Typically I make change to the database structure to reflect a change in the app, which in most cases is the addition of a new feature, and adding in a new feature to the app is time-consuming, so...

**Comment by MeLikeChoco** [comment]
I have begun adding in code to retrieve archetypes and it works with a catch. I only expected one archetype however, some cards can belong to many with weird archetypes like "Change". For example, the card "Mask Change" belongs to 3 different archetypes. Writing logic to choose the best one would prove impossible. For example, the "main" archetype for Mask Change is Change. That is not heard of. Masked Heroes or Heroes would be the correct archetype.

I believe we have two options:
We could either store all the archetypes that are given to us from the card info on Wikia or take the first main one, which may or may not be the best one. 

Edit: Another great example of complicated archetyp-"ing". Abyss Warrior. Is it Abyss-, Abyss, or Warrior?
